config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  
  resources :posts do
    resources :comments
    resources :charges
  end

  resources :tags do
    resources :posts
  end


end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post

    validates :content, length: { maximum: 200 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  after_validation :parse_tags

  has_many :comments, dependent: :destroy
  has_attached_file :image, 
                    styles: { large: "500"},
                    storage: :s3,
                    s3_credentials: {
                      access_key_id: 'AKIAJCXXF7UZZDQ4S4GQ',
                      secret_access_key: Rails.application.secrets.sw3_secret_access_key
                    },
                    bucket: 'faux_instagram'

  has_attached_file :drawing, 
                    styles: { large: "500"},
                    storage: :s3,
                    s3_credentials: {
                      access_key_id: 'AKIAJCXXF7UZZDQ4S4GQ',
                      secret_access_key: Rails.application.secrets.sw3_secret_access_key
                    },
                    bucket: 'faux_instagram'

  validates :image, presence: true
  
  has_and_belongs_to_many :tags, autosave: false

  def save_tags_without_hashtags mytags
    self.tags = mytags.map { |tag| Tag.find_or_create_by(name: tag[1..-1]) }
  end

  def parse_tags
    save_tags_without_hashtags(content.downcase.gsub('#',' #').scan(/\#\w+/)).uniq
  end

  def self.by_tag_or_all(tag_name)
    tag_name ? Tag.find_by(name: tag_name).posts : all
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :posts

  def to_s
    '#' + name
  end

  def to_param
    name
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_new_post, :show_all_tags

  private

  def set_new_post
    @new_post = Post.new
  end

  def show_all_tags
    @all_tags = Tag.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post_for_comment = Post.find(params[:post_id])
    @new_comment = Comment.new
  end

  def create
    @post_for_comment = Post.find(params[:post_id])
    @new_comment = Comment.new params[:comment].permit(:content)
    @new_comment.post = @post_for_comment
    @new_comment.save ? redirect_to(posts_path) : render('new') 
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @new_post = Post.new
  end

  def create
    @post = Post.create params[:post].permit(:title, :content, :image)
    @post.save ? redirect_to(post_path(@post)) : render('new')
  end

  def index
    @posts = Post.by_tag_or_all(params[:tag_id])
    @new_post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update params[:post].permit(:drawing)

    WebsocketRails[:drawing].trigger 'update_drawing', {id: @post.id, drawing: @post.drawing_updated_at, image_url: @post.drawing.url}
    
    redirect_to ('/')
  end

  def destroy
  end

  def show
    @post = Post.find_by(params[:post_id])
    @post_for_comment = Post.find_by(params[:post_id])
    @new_comment = Comment.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_new.html.erb
<div class='add-comment-background'></div>
<div class='add-comment-form col-xs-8 col-sm-8 col-md-8 col-md-offset-2'>

<%= form_for [@post_for_comment, @new_comment] do |form| %>
  
  <%= form.label :content %>
  <%= form.text_area :content %>

  <%= form.submit %>

<% end %>

<a class='add-comment-close'><h1>X</h1></a>

</div>

app/views/comments/new.html.erb
<%= render partial: 'new' %>

app/views/layouts/_header.html.erb
<div id='top_nav'class='row navbar-fixed-top'>
  <div id='top_left_corner' class='col-xs-2 col-sm-2 col-md-2 navbar-fixed-top'>
    <div id='menu'>
      <h4 class="text-center button">
      <a href='#' class='post nav'>Post-it</a>
      <a href='#' class='about nav'>About</a>
      <a href='#' class='about nav'>New Post</a>
      </h4>
    </div>
    <%= render 'layouts/show_tags' %>
  </div>
</div>



<div class='about-page navbar-fixed-top'>
  <div class='about-background'></div>
  <div class='about-content text-center col-xs-8 col-sm-8 col-md-8 col-md-offset-2'>
    <h1>Post an image. Edit an image. Comment on an image.<br/>
    Post-it is a basic Ruby on Rails application completed as a project set at Makers Academy. Code hints and guidance by Alex Peattie. View the code on Github.<br/>Created by Hannah Knights and Tom Schaham......edit text</h1> 
    <a class='about-close'><h1>X</h1></a>
  </div>
</div>

<div class='new-post navbar-fixed-top'>

<%= render new_post_path %>

</div>

app/views/layouts/_show_tags.html.erb
<div id ='tag-sidebar'>

  <% if @all_tags.any? %>

    <% @all_tags.each do |tag| %>

      <h4 class='text-center'>

      <%= link_to tag, tag_posts_path(tag) %>

      </h4>

    <% end %>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'>
</head>
<body>

  <%= render 'layouts/header' %>

  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>


    <%= yield %>



</body>
</html>

app/views/posts/_new.html.erb
<div class='new-post-background'></div>
<div class='new-post-form col-xs-8 col-sm-8 col-md-8 col-md-offset-2'>

  <%= form_for @new_post do |form| %>
    
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :content %>
    <%= form.text_area :content %>


    <%= form.label :image %>
    <%= form.file_field :image %>

    <%= form.submit %>

  <% end %>

  <a class='new-post-close'><h1>X</h1></a>
</div>

app/views/posts/edit.html.erb
<div id ='tag-sidebar' class="navbar-fixed col-lg-2">

  <% if @post.tags.any? %>

    <% @post.tags.each do |tag| %>

      <h4 class='text-center'>

      <%= link_to tag, tag_posts_path(tag) %> 

      </h4>

    <% end %>

  <% end %>

</div>


<div class='edit-post-display post-display col-md-5 col-md-offset-2'>

  <div class='row edit-post-header post-header'>

    <h4>
    <%= @post.title %>
    </h4>
  
  </div>

  <div class='image-container'>

  <% if @post.image_file_name.present? %>

    <div id='original-image'>

    <%= image_tag @post.image.url(:large), class: 'instagram_upload' %>

    </div>

  <% end %>

    <div id='draw'></div>

  </div>
  
  <div class='post-content'>
    
    <%= @post.content %>

  </div>

  <div class='edit-post-tags post-tags'>

      <% if @post.tags.any? %>
        
        <% @post.tags.each do |tag| %>

          <%= link_to tag, tag_posts_path(tag), :class => 'post-tag' %>

        <% end %>

      <% end %>

  </div>

</div>





  <div id='pencil-picker'>
      <form id='pick'>
      <input id='colour' value='#FF6666' type='text' placeholder='Pick a colour'>
      <input id='thickness' type='range' name='thickness' min='1' max='50' value='20'>
      </form>
  </div>

  <div id='eraser-picker'>
    <input id='eraser'type='checkbox' name='erase' value='true'></div>
  </div>

  <%= form_for @post, html: { id: "add_drawing" } do |form| %>

      <%= form.hidden_field :drawing %>

      <%= form.submit %>

  <% end %>

  <% if @post.drawing_file_name.present? %>
    <div id='drawing' style='display: none;'>
      <%= image_tag @post.drawing.url(:large), class: 'instagram_upload' %>
    </div>
  <% end %>


  <input id='canvas-drawing-data' value='#FF6666' type='hidden'>

  <div id='post-id'><%= @post.id %></div>



<script src='https://code.jquery.com/jquery-2.0.3.min.js'></script>
<script>
  window.penColor = $('#colour').val();
  $('#colour').on('change', function() {
    window.penColor = $(this).val();
  });

  window.penThickness = $('#thickness').val();
  $('#thickness').on('change', function() {
    window.penThickness = $(this).val();
  });

  window.eraserAction = $('#eraser').is (':checked');
  $('#eraser').on('change', function() {
    window.eraserAction = $(this).is (':checked');
  });

  var dispatcher = new WebSocketRails(window.location.host + '/websocket');
  var channel = dispatcher.subscribe('drawing')

  function makeCanvasWithPen() {


      function createCanvas(parent, width, height) {
          var canvas = {};
          canvas.node = document.createElement('canvas');
          canvas.context = canvas.node.getContext('2d');
          canvas.node.width = width || 100;
          canvas.node.height = height || 100;
          canvas.node.id = 'canvas-drawing';
          parent.appendChild(canvas.node);

          if($('#drawing img').length){

            var image = new Image;
            image.crossOrigin = '';
            image.src = $('#drawing img').attr('src');
            image.onload = function() {
              canvas.context.drawImage(image, 0, 0);
            }
          }

          return canvas;
      };

      function init(container, canvas, width, height) {

          var ctx = canvas.context;

          function sendData() {

            var drawingData = $('canvas')[0].toDataURL('image/png');

            var postId = $('#post-id').text();

             // var drawingData = $('canvas')[0].toBlob();

            channel.trigger('updated', {data: drawingData, postId: postId });

            // console.log('This is coming from sendData ---->');
            // console.log(drawingData.value);
            // console.log('<----This is coming from sendData');
          
          // console.log((document.getElementById('canvas-drawing')).toDataURL('image/png'));

          };

          // define a custom fillCircle method
          ctx.fillCircle = function(x, y, radius, fillColor, erase) {
              if (erase == true) 
                {
                this.globalCompositeOperation="destination-out";
                }
              else
                {
                this.globalCompositeOperation="source-over"
                }
              this.fillStyle = fillColor;
              this.beginPath();
              this.moveTo(x, y);
              this.arc(x, y, radius, 0, Math.PI * 2, false);
              this.fill();
          };
          

          // bind mouse events
          canvas.node.onmousemove = function(e) {
              // console.log('hi')
              if (!canvas.isDrawing) {
                 return;
              }
              var x = e.pageX - $(this).offset().left;
              var y = e.pageY - $(this).offset().top;
              var radius = window.penThickness;
              var fillColor = window.penColor;
              var erase = window.eraserAction
              ctx.fillCircle(x, y, radius, fillColor, erase);
              
              sendData()  
          
          };
          canvas.node.onmousedown = function(e) {
              canvas.isDrawing = true;
          };
          canvas.node.onmouseup = function(e) {
              canvas.isDrawing = false;
          };
      };

      var container = document.getElementById('draw');

      var height = $('#original-image').height()

      var width = $('#original-image').width()

      var canvas = createCanvas(container, width, height);


      
      init(container, canvas, width, height);

  };

  function saveCanvasImage() {


      function sendImage(drawingSource) {

          document.getElementById('add_drawing').post_drawing.value = drawingSource;

      };

      var drawing = document.getElementById('canvas-drawing');

      var drawingSource = drawing.toDataURL('image/png');

      sendImage(drawingSource)

  };


  $(document).ready(function(){

      
      var drawingDataInput = $('#canvas-drawing-data');

      console.log(drawingDataInput);
      console.log(drawingDataInput.val());



      $(window).load (function() {

          makeCanvasWithPen();

      });


      $('#add_drawing').on ('submit', function() {

          saveCanvasImage()

      });


      $('#eraser').click (function () {
        
        var eraserOn = $(this);
          
          if (eraserOn.is (':checked')) {
            console.log('Success!')
            console.log($(this).val())
            console.log(window.eraserAction)
          }

      });

  });


</script>

app/views/posts/index.html.erb
<div class= 'container'>

  <div class='row'>

  <% if @posts.none? %>
  No posts have been made yet!
  <% end %>


  <% @posts.each do |post| %>


    <div class='post-display col-md-6 col-md-offset-4'>


      <div class='row post-header'>

        <span class='glyphicon glyphicon-pencil post-title-icon'></span>
        <h4 class='post-title'>
        <%= link_to post.title, post_path(post) %>
        </h4> 

      </div>

      <div class='image-container'>     

        <% if post.image_file_name.present? %>

          <div class='original-image'>

          <%= image_tag post.image.url(:large), class: 'instagram_upload' %>

          </div>

        <% end %>

        <% if post.drawing_file_name.present? %>

          <div class='drawn-image'>

          <div class='drawing_updated_at' data-id='<%= post.id %>'><%= post.drawing_updated_at %></div>

          <%= image_tag post.drawing.url(:large), class: 'instagram_upload', id: 'test', data: {id: post.id } %>

          </div>

        <% end %>

      </div>

      <div class='post-content'>

        <%= post.content %>

      </div>

      
      <% post.comments.each do |comment| %>

      <div class='post-comments'>

        > 
        <%= comment.content %>
          
      </div>

      <% end %>

      
      <div class='post-tags'>

      <% if post.tags.any? %>
        
        <% post.tags.each do |tag| %>

          <%= link_to tag, tag_posts_path(tag), :class => 'post-tag' %>

        <% end %>

      <% end %>

      </div>


      <div class='row post-buttons'>

      <%= button_to "Add a Comment", new_post_comment_path(post), :class => 'post-button', :method => :get %>

      <%= button_to "Edit this Post", edit_post_path(post), :class => 'post-button', :method => :get %>

      </div>

      
    </div>

  <% end %>
  
  </div>


</div>

<script>

  sortPosts = function() {

    return $(".row > .post-display").tsort('.drawing_updated_at', {
      order: 'desc'
    });

  };

  $(document).ready (function() {

    return sortPosts();

    });

    var dispatcher = new WebSocketRails(window.location.host + '/websocket');

    var channel = dispatcher.subscribe('drawing');

    channel.bind('update_drawing', function(post){

      console.log('This is the post image url -->')
      console.log(post.image_url)
      console.log('This is the post -->')
      console.log(post)

 
      $('.drawing_updated_at[data-id="' + post.id + '"]').text(post.drawing); 
      $('.instagram_upload[data-id="' + post.id + '"]').attr('src', post.image_url);

      return sortPosts();


    });


    channel.bind('updated', function(msg) {
      console.log('hello');
      console.log(msg);

      var liveDrawing = $('.instagram_upload[data-id="' + msg.postId + '"]')[0]

      // console.log(msg.data)
      // console.log(liveDrawing.src)
      // console.log(msg.postId)

      liveDrawing.src = msg.data;

    })

</script>

app/views/posts/new.html.erb
<%= render new_post_path %>

app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>

<% if @post.tags.any? %>
Tags:
  <% @post.tags.each do |tag| %>
    <%= link_to tag, tag_posts_path(tag) %>
  <% end %>
<% end %>

<% if @post.image_file_name.present? %>
  <%= image_tag @post.image.url(:large), class: 'instagram_upload' %>
<% end %>

<% @post.comments.each do |comment| %>
  <%= comment.content %>
<% end %>

<a href='#' class='comment-link'>Add a Comment</a>


Buy:
<%= form_tag post_charges_path(@post) do %>
  <article>
    <label class="amount">
      <span>Amount: £5.00</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets.stripe_public_key %>"
          data-description="A month's subscription"
          data-amount="500"
          data-currency="GBP"></script>
<% end %>

<div class='add-comment navbar-fixed-top'>
  <%= render 'comments/new' %>
</div>